### ISSUE TITLE
Extend renaming capability to include folder names

### ISSUE THREAD

**Issue by ghost** [ligershark/pecan-waffle#11]
Need ability to change folder names just like file names get changed currently

**Comment by sayedihashimi** [comment]
Thanks yes this is needed to support multi-project templates especially.

**Comment by sayedihashimi** [comment]
@managedcoder I think we can close this, please reopen if you have any issues.

**Comment by ghost** [comment]
Yep, this is fixed

**Comment by ghost** [comment]
Opps!  Meant to close this
