### ISSUE TITLE
Project structure changed from flat in template src to bouble root in generated solution

### ISSUE THREAD

**Issue by ghost** [ligershark/pecan-waffle#19]
The template source project has a flat folder structure where the .sln  file, packages folder, .vs folder, and all project folders (Droid, iOS, Win, etc) are all live in the root folder of the solution.  The problem is that in the generated solution has a generated folder structure where the .sln file, packages folder, and .vs folder are in the root folder but the project folders are pushed down a level under a second root folder.

Why isn’t that source folder structure translating "as is" to generated folder structure?

**Comment by sayedihashimi** [comment]
I fixed it but now that I'm looking at it, I will need to make this an option. The new behavior is more suited for multiple projects.

**Comment by ghost** [comment]
Ok, I will close the issue.  When you say it will need to be an option, would that mean there would be some setting in the pw-templateinfo.ps1 file that I would set to tell it to flatten the folder structure?

**Comment by sayedihashimi** [comment]
There is an option for this now see #20
