### ISSUE TITLE
Execute-CommandString not recognized when installing

### ISSUE THREAD

**Issue by codewithtyler** [ligershark/pecan-waffle#2]
When installing `pecan-waffle` and attempting to add the `aspnet-empty` project I get the following error messages.

![pecan-waffle_install](https://cloud.githubusercontent.com/assets/2483249/12870894/098794b0-cd20-11e5-9be8-d16a92f0d78c.PNG)

**Comment by sayedihashimi** [comment]
In https://github.com/ligershark/pecan-waffle/commit/708551cf3d609fec4db2e44022a92eefb98ea601 I have reworked the install script. In the previous it was using `Add-TemplateSource` to the repo to get the templates. Now the install script downloads the repo as a .zip file, extracts contents, loads module and then calls `Add-TemplateSource` on the local folder. So it no longer requires `git.exe` to be on the path by default and it doesn't go down the path of calling `Execute-CommandString` at all.

This should now be fixed so closing. Can you try the latest install script?

**Comment by codewithtyler** [comment]
Install works great now! I didn't get any errors and I was able to add the template source I made last night and then create a new project with the source with no problems.

**Comment by sayedihashimi** [comment]
OK great. I created a `dev` branch to keep master clean.
I'm going to see what I can do about item templates. The existing support should work for multi-project templates. You just put the file at the root instead of at the project level.
