### ISSUE TITLE
Question: where can i find a list of all commands

### ISSUE THREAD

**Issue by MikaelPorttila** [ligershark/pecan-waffle#29]
hi, Is there any list with all commands?
Trying to remove a single template from the show-templates list but all i can find is the clearAllTemplates-cmd.

**Comment by sayedihashimi** [comment]
@MikaelPorttila the best way to see command is to invoke `Get-Command -Module pecan-waffle -CommandType Function`.

Currently I have some functions exported which should be hidden. #30 will fix that.

Below I've executed the command and added `***` next to the functions which should be exported. You can ignore the rest, they will be removed from the export list when #30 is fixed.

<pre><code>
> Get-Command -Module pecan-waffle -CommandType Function
    CommandType     Name                                               ModuleName
    -----------     ----                                               ----------
****Function        Add-PWTemplateSource                               pecan-waffle
****Function        Clear-PWTemplates                                  pecan-waffle
    Function        Copy-ItemRobocopy                                  pecan-waffle
    Function        Copy-TemplateSourceFiles                           pecan-waffle
    Function        Ensure-DirectoryExists                             pecan-waffle
    Function        Get-NewTempDir                                     pecan-waffle
****Function        Get-PecanWaffleVersion                             pecan-waffle
****Function        Get-PWTemplates                                    pecan-waffle
    Function        Get-Robocopy                                       pecan-waffle
    Function        Invoke-CommandString                               pecan-waffle
****Function        New-PWItem                                         pecan-waffle
****Function        New-PWProject                                      pecan-waffle
****Function        Update-PWRemoteTemplates                           pecan-waffle
</code></pre>

**Comment by MikaelPorttila** [comment]
@sayedihashimi Thanks for the response :) 
I couldn't find any delete cmd for a single template though, is there any easy way to do this?

**Comment by sayedihashimi** [comment]
@MikaelPorttila the templates are stored in `$Global:pecanwafflesettings.Templates` as a standard array. When I try to remove from it I get an error, see below.

```
> $Global:pecanwafflesettings.Templates.Remove( $Global:pecanwafflesettings.Templates[0] )
Exception calling "Remove" with "1" argument(s): "Collection was of a fixed size."
At line:1 char:1
+ $Global:pecanwafflesettings.Templates.Remove( $Global:pecanwafflesettings.Templa ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NotSupportedException
```

So to fix this we would need to add a new functions, lets say `Remove-PWTemplate` which takes takes a `[string[]]` of names to remove. Then it will repopulate the array and skip any templates with the give names.

I am busy working in some other areas so I won't have time soon to work on this. If you send a PR to the [`dev`](https://github.com/ligershark/pecan-waffle/tree/dev) branch I will review and merge.

**Comment by MikaelPorttila** [comment]
PR incoming.
Please check ligershark/pecan-waffle#31
