### ISSUE TITLE
Project folder when using template

### ISSUE THREAD

**Issue by mm98** [ligershark/pecan-waffle#37]
When using pacan template, the project will be placed in a sub-folder containing the project name. This results in the following folder structure:

**Projects folder:** C:\Projects\
**Project name:**   SampleProject

> C:\Projects\SampleProject\SampleProject\

When creating projects in VS, they are placed in the first folder ex. no sub-folder created.
I could uncheck "Create directory for solution", this then results in packages folder in:

> C:\projects\packages

This is also a common problem with VSTemplates. Could this be changed with pacan waffle templates?

Possible solution on Stackoverflow
[http://stackoverflow.com/questions/3882764/issue-with-visual-studio-template-directory-creation](http://stackoverflow.com/questions/3882764/issue-with-visual-studio-template-directory-creation)

**Comment by sayedihashimi** [comment]
@mm98 thanks for the report. I see what you mean. I'm looking into it.

**Comment by sayedihashimi** [comment]
@mm98 OK I think I've fixed it. The fix is in `0.0.22-beta` nuget package. I think I got everything fixed here so I'll close this. Please try it. If it doesn't work as you expect please re-open this with details.

**Comment by mm98** [comment]
I have updated the pecan project to `0.0.22-beta`. Two nodes were removed in `pecan-waffle-settings.props` (overwritten on package update).

When i Build the solution I get an error, that it can't find the ProjectId defined in `source.extension.vsixmanifest`. I have double checked, and the ProjectId's are the same in `source.extension.vsixmanifest` and `_project.vstemplate`. 

Do i need to make any changes to `_project.vstemplate` or `pw-templateinfo.ps1` ?

**Error List output**
`Extension 'MultiProjectTemplate.Carsten Petersen.ef4a14f9-7ab6-4ede-8716-81ea0e1cee9a' could not be found. Please make sure the extension has been installed.	MultiProjectTemplate`

**Comment by mm98** [comment]
I can confirm that it is working when unchecking `Create directory for solution` in `New project` window. The `packages` folder is placed in the project root folder (#38).

**Just a thought ...**
Is there any way to change this, so one may not need to uncheck `Create directory for solution`? 

This is kinda a new way to creating project (has to remember to uncheck) compared to the usual way you'll do a new project in VS, where the folder structure is "correct" by default.

**Comment by sayedihashimi** [comment]
@mm98 when using pecan-waffle you should be getting the same results as using a standard console app project after my changes. Are you seeing something different?

**Comment by mm98** [comment]
The only difference I see, is that the `packages` folder is placed correctly in the project root folder when unchecking `Create directory for solution`. If I leave it checked, the folder structure is still as mentioned previously ex. `C:\Projects\ProjectName\ProjectName\`...

This is not a bug - VSTemplates has the same "challenge" .. just a feature request on my part =)
